### ISSUE TITLE
Rules based models for Error Analysis and MimicExplainer

### ISSUE THREAD

**Issue by marcelned** [microsoft/responsible-ai-widgets#698] opened 2021-07-19 09:12 UTC
How would one go about using the `MimicExplainer` for a rules based model like so:

```console
c0 <= 1.15681171417 and c0 > -0.680330395699 and c1 <= 1.08434700966
c0 > -0.841694712639 and c1 <= 0.687212407589 and c1 > -1.21965646744
c0 <= 1.03912234306 and c0 > -0.663101434708 and c1 <= 1.27947068214
c0 > -0.841694712639 and c1 <= 0.687212407589 and c1 > -1.43224191666
```

This type of if-then ruleset could potentially be generated with [SKOPErules](https://skope-rules.readthedocs.io/en/latest/index.html).

Initially I tried creating my own class with a `predict` method for `MimicExplainer`  but it seems there is more going on in the background (doesn't work)

**Comment by imatiach-msft** [comment] 2021-07-19 23:19
@marcelned that should just work, could you send us an example notebook that reproduces the issue?  How did you define the predict function?  Is this for regression scenario, note for classification you will need predict_proba as well?

**Comment by gaugup** [comment] 2021-11-16 00:37
@marcelned, can you provide some example notebook that @imatiach-msft has requested?

If you are not experiencing the issue anymore, then maybe we can close this issue. It's been more than three months.

Regards,

**Comment by gaugup** [comment] 2021-11-18 18:08
Closing due to no response from the submitter.

**Closed by gaugup** 2021-11-18 18:08 UTC
Labels: question
