### ISSUE TITLE
[Error Analysis] Size and zoom consistency (normal vs full screen mode)

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#227] opened 2020-12-19 01:39 UTC
[Obj size on the Top info area]
When I open the full screen, the overall objects on the top information area became bigger. Regardless of the screen status, all objects should have the same size. I am unsure of how this happens.

[Zoom]
When I load the dashboard and I open the full screen, the treemap should be centering and its zoom should be 100%. It seems to be above 100% zoom in the full screen.

<img width="1010" alt="Screen Shot 2020-12-18 at 4 56 00 PM" src="https://user-images.githubusercontent.com/1608824/102677572-ed0dd900-4157-11eb-9409-37f81b1e4374.png">
<img width="1408" alt="Screen Shot 2020-12-18 at 5 40 20 PM" src="https://user-images.githubusercontent.com/1608824/102677636-2e05ed80-4158-11eb-9f4f-ed16ed52f3c9.png">

**Comment by imatiach-msft** [comment] 2021-10-04 14:18
closing this issue as zoom has been removed based on latest UI designer guidelines so the issue is no longer relevant

**Closed by imatiach-msft** 2021-10-04 14:18 UTC
Labels: Error Analysis
